// <auto-generated />
using System;
using LOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LOS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910133938_LoanApplicationAdded")]
    partial class LoanApplicationAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LOS.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("PassportSeries")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Snils")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("PassportSeries", "PassportNumber")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("LOS.Domain.Clients.Employment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("employments", (string)null);
                });

            modelBuilder.Entity("LOS.Domain.Clients.Income", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("incomes", (string)null);
                });

            modelBuilder.Entity("LOS.Domain.LoanApplications.LoanApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RequestedTermMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("loan_applications", (string)null);
                });

            modelBuilder.Entity("LOS.Domain.LoanProducts.LoanProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseInterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxTermMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinTermMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("loan_products", (string)null);
                });

            modelBuilder.Entity("LOS.Domain.Clients.Employment", b =>
                {
                    b.HasOne("LOS.Domain.Clients.Client", "Client")
                        .WithMany("Employments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LOS.Domain.Clients.Income", b =>
                {
                    b.HasOne("LOS.Domain.Clients.Client", "Client")
                        .WithMany("Incomes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LOS.Domain.LoanApplications.LoanApplication", b =>
                {
                    b.OwnsMany("LOS.Domain.LoanApplications.ApplicationTimelineEntry", "Timeline", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id1")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id1"));

                            b1.Property<string>("ChangedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("FromStatus")
                                .HasColumnType("text");

                            b1.Property<string>("ToStatus")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ApplicationId", "Id1");

                            b1.ToTable("application_timeline", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("LOS.Domain.LoanProducts.LoanProduct", b =>
                {
                    b.OwnsOne("LOS.Domain.LoanProducts.EligibilityCriteria", "Eligibility", b1 =>
                        {
                            b1.Property<Guid>("LoanProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CitizenshipRequired")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasDefaultValue("RU")
                                .HasColumnName("eligibility_citizenship_required");

                            b1.Property<int>("MaxAge")
                                .HasColumnType("integer")
                                .HasColumnName("eligibility_max_age");

                            b1.Property<decimal>("MaxDebtToIncomeRatio")
                                .HasColumnType("decimal(3,2)")
                                .HasColumnName("eligibility_max_debt_to_income_ratio");

                            b1.Property<int>("MinAge")
                                .HasColumnType("integer")
                                .HasColumnName("eligibility_min_age");

                            b1.Property<decimal>("MinMonthlyIncome")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("eligibility_min_income");

                            b1.Property<int>("MinWorkExperienceMonths")
                                .HasColumnType("integer")
                                .HasColumnName("eligibility_min_work_experience_months");

                            b1.HasKey("LoanProductId");

                            b1.ToTable("loan_products");

                            b1.WithOwner()
                                .HasForeignKey("LoanProductId");
                        });

                    b.OwnsOne("LOS.Domain.LoanProducts.ProductFees", "Fees", b1 =>
                        {
                            b1.Property<Guid>("LoanProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("EarlyRepaymentFeePercent")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("fee_early_repayment_percent");

                            b1.Property<bool>("InsuranceRequired")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("fee_insurance_required");

                            b1.Property<decimal>("OriginationFeePercent")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("fee_origination_percent");

                            b1.HasKey("LoanProductId");

                            b1.ToTable("loan_products");

                            b1.WithOwner()
                                .HasForeignKey("LoanProductId");
                        });

                    b.Navigation("Eligibility")
                        .IsRequired();

                    b.Navigation("Fees")
                        .IsRequired();
                });

            modelBuilder.Entity("LOS.Domain.Clients.Client", b =>
                {
                    b.Navigation("Employments");

                    b.Navigation("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
